name: trial-postgres

volumes:
  postgres_data:

networks:
  frontend:
  backend:

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: unless-stopped
    networks:
      - backend
    ports:
      - ${PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: 2

  adminer:
    container_name: adminer-for-postgres
    image: adminer:latest
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend
      - frontend
    ports:
      - ${PORT_UI-8080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB: postgres
      ADMINER_DESIGN: dracula
      # Dev ONLY
      # ADMINER_SINGLE_USER: "true"
      # ADMINER_USERNAME: ${POSTGRES_USER:-root}
      # ADMINER_PASSWORD: ${POSTGRES_PASSWORD}
