volumes:
  postgres_data:

networks:
  frontend:
  backend:

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    networks:
      - backend
    env_file: .env
    ports:
      - ${PORT-5432}:5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgres/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  adminer:
    container_name: adminer-for-postgres
    image: adminer
    depends_on:
      - postgres
    restart: always
    networks:
      - backend
      - frontend
    env_file: .env
    ports:
      - ${PORT_UI-8081}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
